//
// Generated file, do not edit! Created by opp_msgtool 6.2 from BlockchainMsg.msg.
//

#ifndef __BLOCKCHAINMSG_M_H
#define __BLOCKCHAINMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TransactionMsg;
class BlockMsg;
/**
 * Class generated from <tt>BlockchainMsg.msg:1</tt> by opp_msgtool.
 * <pre>
 * message TransactionMsg
 * {
 *     int senderId;
 *     int receiverId;
 *     double amount;
 *     string timestamp;
 *     string signature;
 *     string transactionHash;
 * }
 * </pre>
 */
class TransactionMsg : public ::omnetpp::cMessage
{
  protected:
    int senderId = 0;
    int receiverId = 0;
    double amount = 0;
    omnetpp::opp_string timestamp;
    omnetpp::opp_string signature;
    omnetpp::opp_string transactionHash;

  private:
    void copy(const TransactionMsg& other);

  protected:
    bool operator==(const TransactionMsg&) = delete;

  public:
    TransactionMsg(const char *name=nullptr, short kind=0);
    TransactionMsg(const TransactionMsg& other);
    virtual ~TransactionMsg();
    TransactionMsg& operator=(const TransactionMsg& other);
    virtual TransactionMsg *dup() const override {return new TransactionMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual int getReceiverId() const;
    virtual void setReceiverId(int receiverId);

    virtual double getAmount() const;
    virtual void setAmount(double amount);

    virtual const char * getTimestamp() const;
    virtual void setTimestamp(const char * timestamp);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);

    virtual const char * getTransactionHash() const;
    virtual void setTransactionHash(const char * transactionHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransactionMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransactionMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>BlockchainMsg.msg:10</tt> by opp_msgtool.
 * <pre>
 * message BlockMsg
 * {
 *     string prevBlockHash;
 *     string merkleRoot;
 *     int nonce;
 *     string currentBlockHash;
 *     bool isVerified;
 * }
 * </pre>
 */
class BlockMsg : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string prevBlockHash;
    omnetpp::opp_string merkleRoot;
    int nonce = 0;
    omnetpp::opp_string currentBlockHash;
    bool isVerified_ = false;

  private:
    void copy(const BlockMsg& other);

  protected:
    bool operator==(const BlockMsg&) = delete;

  public:
    BlockMsg(const char *name=nullptr, short kind=0);
    BlockMsg(const BlockMsg& other);
    virtual ~BlockMsg();
    BlockMsg& operator=(const BlockMsg& other);
    virtual BlockMsg *dup() const override {return new BlockMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getPrevBlockHash() const;
    virtual void setPrevBlockHash(const char * prevBlockHash);

    virtual const char * getMerkleRoot() const;
    virtual void setMerkleRoot(const char * merkleRoot);

    virtual int getNonce() const;
    virtual void setNonce(int nonce);

    virtual const char * getCurrentBlockHash() const;
    virtual void setCurrentBlockHash(const char * currentBlockHash);

    virtual bool isVerified() const;
    virtual void setIsVerified(bool isVerified);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BlockMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BlockMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TransactionMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<TransactionMsg*>(ptr.get<cObject>()); }
template<> inline BlockMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<BlockMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BLOCKCHAINMSG_M_H

